# -*- coding: utf-8 -*-
"""Listas y Tuplas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17scexU7SHTolbuwZfreYc_olGcZAZGo5
"""

# Listas => estructura de datos compuesto por un conjunto de valores ordenados
lista = [] # declarando una lista como vacio
lista2 = [1, "dos", 3, 4] # declarando lista con valores

#imprimir listas
print(lista)

print(lista2) 
print(lista2[0]) #imprime primer elemento de la lista
print(lista2[2]) #imprime segundo elemento de la lista
print(lista2[0:3]) #imprime los elemento desde la posicion 0 hasta la posicion unos nos que posicion 2 de la lista

# metodos
#append => agregar un elemento a la lista
lista.append("hola")
print(lista)

lista.append("mundo")
print(lista)

#remove => elimina elemento de la lista
print(lista2)
lista2.remove("dos")
print(lista2)

lista.remove("mundo")
print(lista)

#index devulve el indice del elemento
lista2.index(1)

# insertar elemento en un posicion
lista.insert(0, "lima")
print(lista)

#pop => Quita el elemento en la posición y lo devuelve. Si no se especifica un índice quita y devuelve el último elemento de la lista
lista2.pop(0)

print(lista2)

#clear => quita todo los elementos de la lista
lista2.clear()
print(lista2)

#Tuplas estructura de datos ordenada estatica
tupla = () # declarando una tupla vacio
tupla2 = tuple() # declarando tupla vacion

tupla = (1, "dos", 3, False)
tupla2 = ([1,2], "hola", True)

print(tupla)
print(tupla2)

#acceder a los valores de una dupla
print(tupla[2])
print(tupla2[0])

datos = ("Jorge", "Gonzalez", 30, "M")
nombre, apellido, edad, genero = datos

nombre

apellido

genero

#Iteracion en una lista
for item in lista:
  print(item)

for item in datos:
  print(item)

# elemento existe en lista
print(lista2)
1 in lista2

print(tupla2)
False in tupla2